config/routes.rb
Rails.application.routes.draw do

  root 'manufacturers#index'

  get '/login' => 'sessions#new', as: :login
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy', as: :logout

  resources :manufacturers do

    resources :factories
    resources :car_models
  end

end

app/models/car_model.rb
class CarModel < ActiveRecord::Base
    belongs_to :manufacturer
    has_many :production_lines
    has_many :factories, :through => :production_lines
    validates :name, presence: true, uniqueness: true

end

app/models/factory.rb
class Factory < ActiveRecord::Base
  belongs_to :manufacturer
  has_many :car_models, :through => :production_lines
  has_many :production_lines
  validates :city, uniqueness: true, presence: true
  validates :state, uniqueness: true, presence: true

end

app/models/manufacturer.rb
class Manufacturer < ActiveRecord::Base
	has_many :car_models
	has_many :factories

end

app/models/production_line.rb
class ProductionLine < ActiveRecord::Base
  belongs_to :factory
  belongs_to :car_model
end

app/models/production_lines.rb
class ProductionLines < ActiveRecord::Base
  belongs_to :factory
  belongs_to :car_model
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private
  def require_login
    unless session[:user]
      redirect_to login_url
      return false
    end
  end

end

app/controllers/car_models_controller.rb
class CarModelsController < ApplicationController
  before_action :require_login, only: [:new, :create]

  def new
    @manufacturer = Manufacturer.find(params[:manufacturer_id])
    @car_model = CarModel.new
  end

  def create
    @manufacturer = Manufacturer.find(params[:manufacturer_id])

    @car_model = @manufacturer.car_models.create(car_model_params)
    if @car_model.valid?
      redirect_to manufacturer_car_model_path(@manufacturer, @car_model), notice: "#{@car_model.name} has been created"
    else
      render 'new'
    end
  end

  def show
    @manufacturer = Manufacturer.find(params[:manufacturer_id])
    @car_model = @manufacturer.car_models.find(params[:id])
  end



  private

  def car_model_params
    params.require(:car_model).permit(:name, :mpg, :price)
  end
end

app/controllers/factories_controller.rb
class FactoriesController < ApplicationController

  skip_before_action :require_login, only: [:show]

  def show

  end

  def new
    @manufacturer = Manufacturer.find(params[:manufacturer_id])
    @factory = Factory.new
  end

  def create
    @manufacturer = Manufacturer.find(params[:manufacturer_id])

    @factory = @manufacturer.factories.create(factory_params)
    if @factory.valid?
      redirect_to manufacturer_path(@manufacturer)
    else
      render 'new'
    end
  end


  private

  def factory_params
    params.require(:factory).permit(:city, :state, :unionized)
  end
end

app/controllers/manufacturers_controller.rb
class ManufacturersController < ApplicationController
  before_action :require_login, only: [:edit, :update, :destroy]
  before_action :get_manufacturer, except: [:index]

  def index
    @manufacturers = Manufacturer.all
  end

  def show
  end

  def edit
  end

  def update
    @manufacturer.update(params.require(:manufacturer).permit(:name, :domestic))
    flash[:notice] = "Manufacturer successfully updated!"
    redirect_to manufacturer_url
  end

  def destroy
    @manufacturer.destroy
    redirect_to root_url
  end

  private

  def get_manufacturer
    @manufacturer = Manufacturer.find(params[:id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(email: params[:email])
    if user && user.authenticate(params[:password])
      session[:user] = params[:email] # I still don't really understand the session[] magic
      redirect_to root_path
    else
      flash[:error] = "FAIL"
      render :new
    end
  end

  def destroy
    session[:user] = nil
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/car_models_helper.rb
module CarModelsHelper
end

app/helpers/factories_helper.rb
module FactoriesHelper
end

app/helpers/manufacturers_helper.rb
module ManufacturersHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/car_models/new.html.erb
<h1>New Car Model</h1>

<%= form_for([@manufacturer, CarModel.new]) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
<br>
  <%= f.label :mpg %>
  <%= f.text_field :mpg %>
<br>
  <%= f.label :price %>
  <%= f.text_field :price %>
<br>
    <%= f.button "New Car" %>
<% end %>

app/views/car_models/show.html.erb
<h1><%= @car_model.name %></h1>

app/views/factories/new.html.erb
<h1>New Factory</h1>

<%= form_for([@manufacturer, @factory]) do |f| %>
  <%= f.label :city %>
  <%= f.text_field :city %>
<br>
  <%= f.label :state %>
  <%= f.text_field :state %>
<br>
  <%= f.label :unionized, "Yes" %>
  <%= f.radio_button :unionized, true %>
<br>
  <%= f.label :unionized, "No" %>
  <%= f.radio_button :unionized, false %>
<br>
  <%= f.button "Create New Factory" %>
<% end %>

app/views/factories/show.html.erb
<h1>Factories#show</h1>
<p>Find me in app/views/factories/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RorQuizApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <% flash.each do |key, value| %>
    <p class="flash">
      <%= value %>
    </p>
  <% end %>

<% if session[:user] %>
  <p><%= "Currently logged in as #{session[:user]}." %></p>
  <p><%= link_to "Log out", logout_path, method: :delete %></p>
<% else %>
  <p><%= link_to "Log in", login_path %></p>
<% end %>

<%= yield %>

</body>
</html>

app/views/manufacturers/edit.html.erb
<h1>Edit <%= @manufacturer.name %></h1>
  <%= form_for @manufacturer do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.radio_button :domestic, true %>
  <%= f.label :domestic, 'Domestic', :value => 'true' %>
  <%= f.radio_button :domestic, false %>
  <%= f.label :foreign, 'Foreign', :value => 'false' %>
  <%= f.submit 'Edit my data' %>
<% end %>

<p><%= button_to "Delete Manufacturer", manufacturer_path(@manufacturer), method: :delete,
                                                                        data: { confirm: "Are you sure? "}%></p>

<p><%= link_to "Home", root_path %></p>

app/views/manufacturers/index.html.erb
<h1>Manufacturers</h1>

<ul>
  <% @manufacturers.each do |manufacturer| %>
    <li class = "<%= "domestic_#{manufacturer.domestic}" %>"><%= link_to manufacturer.name, manufacturer_path(manufacturer) %></li>
  <% end %>
</ul>

<p><%= link_to "New Manufacturer", new_manufacturer_path %></p>
<p><div id="show_domestic">Show Domestic</div></p>
<p><div id="show_foreign">Show Foreign</div></p>
<p><div id="show_all">Show All</div></p>

app/views/manufacturers/show.html.erb
<h1> <%= @manufacturer.name %> </h1>

<p> <%= @manufacturer.name %> is a <% if @manufacturer.domestic %> domestic <% else %> foreign <% end %> car manufacturer.</p>
  <ul>
    <% @manufacturer.car_models.each do |car| %>
      <li><%= car.name %></li>
    <% end %>
  </ul>

  <table>
    <tr>
      <th>City</th>
      <th>State</th>
      <th>Union?</th>
    </tr>
    <% @manufacturer.factories.each do |fac| %>
      <tr>
        <td><%= fac.city  %></td>
        <td><%= fac.state %></td>
        <td><%= fac.unionized %></td>
      </tr>
    <% end %>
  </table>


<p><%= link_to "Edit", edit_manufacturer_path(@manufacturer) %></p>

<p><%= link_to "New Car Model", new_manufacturer_car_model_path(@manufacturer) %></p>
<p><%= link_to "New Factory", new_manufacturer_factory_path(@manufacturer) %></p>

<p><%= link_to "Home", root_path %></p>